// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiCW-h3m0qDY08JusiELDclhCwz7gpDg0',
    appId: '1:605423983769:web:78a027dd7e6578beba6c08',
    messagingSenderId: '605423983769',
    projectId: 'csc4360messageb',
    authDomain: 'csc4360messageb.firebaseapp.com',
    storageBucket: 'csc4360messageb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIYY5Cyo0iOrKC6-2CmyA2b_ntZxP56iE',
    appId: '1:605423983769:android:a65233dd8dee5135ba6c08',
    messagingSenderId: '605423983769',
    projectId: 'csc4360messageb',
    storageBucket: 'csc4360messageb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAYxH7Khh1b_5JoQf1t6CxamHHfi6heus',
    appId: '1:605423983769:ios:074546352d255eb4ba6c08',
    messagingSenderId: '605423983769',
    projectId: 'csc4360messageb',
    storageBucket: 'csc4360messageb.firebasestorage.app',
    iosBundleId: 'com.example.messageboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAYxH7Khh1b_5JoQf1t6CxamHHfi6heus',
    appId: '1:605423983769:ios:074546352d255eb4ba6c08',
    messagingSenderId: '605423983769',
    projectId: 'csc4360messageb',
    storageBucket: 'csc4360messageb.firebasestorage.app',
    iosBundleId: 'com.example.messageboard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiCW-h3m0qDY08JusiELDclhCwz7gpDg0',
    appId: '1:605423983769:web:bafa7b222b4658d3ba6c08',
    messagingSenderId: '605423983769',
    projectId: 'csc4360messageb',
    authDomain: 'csc4360messageb.firebaseapp.com',
    storageBucket: 'csc4360messageb.firebasestorage.app',
  );

}